local _, L = ...;

if (GetLocale() == "ptBR") then
 -- General strings
 L["Click on a world quest in the objective tracking window to search for a group."] = "Clique em uma Missão Mundial na janela de rastreamento de objetivo para procurar um grupo."
 L["You already are in a group for this world quest."] = "Você ja esta em um grupo para esta Missão."
 L["Searching for a group for world quest |c00bfffff%s|c00ffffff..."] = "Procurando um grupo para a Missão Mundial |c00bfffff%s|c00ffffff..."
 L["You have not been applied to %d group(s) because their leader was blacklisted. You can use |c00bfffff/wqgf unbl |c00ffffffto clear the blacklist."] = "Você não foi convidade para o grupo %d pois o lider esta na Lista Negra  |c00bfffff/wqgf unbl |c00ffffffpara limpar a Lista."
 L["A new group finder entry has been created for |c00bfffff%s|c00ffffff in |c00bfffff%s|c00ffffff."] = "Um novo grupo foi criada para |c00bfffff%s|c00ffffff em |c00bfffff%s|c00ffffff."
 L["You have been applied to |c00bfffff%d|c00ffffff group(s) for the world quest |c00bfffff%s|c00ffffff."] = "Você foi convidado para o grupo |c00bfffff%d|c00ffffff para a Missão Mundial |c00bfffff%s|c00ffffff."
 L["You are not in the right location for this world quest."] = "Você não esta no loca certo para esta Missão Mundial."
 L["You have joined |c00bfffff%s|c00ffffff's group for |c00bfffff%s|c00ffffff. Have fun!"] = "Você entrou no grupo |c00bfffff%s|c00ffffff's para |c00bfffff%s|c00ffffff. Se divirta !"
 L[":)"] = "Acabou ! :)"
 L["This type of world quest cannot be accomplished as a group."] = "Esse tipo de Missão Mundial não pode ser completada em grupo."
 L["Your group is now doing the world quest |c00bfffff%s|c00ffffff. You already have completed this world quest."] = "O seu grupo esta fazendo agora a Missão Mundial |c00bfffff%s|c00ffffff. Você ja completou esta Missão."
 L["Your group is now doing the world quest |c00bfffff%s|c00ffffff."] = "O seu grupo esta fazendo agora a Missão Mundial |c00bfffff%s|c00ffffff."
 L["Your group is no longer doing the world quest |c00bfffff%s|c00ffffff."] = "O seu grupo não esta mais fazendo a Missão Mundial |c00bfffff%s|c00ffffff."
 L["Your group is now doing the world quest |c00bfffff%s|c00ffffff. You are not eligible to do this world quest."] = "O seu grupo esta agora fazendo a Missão Mundial |c00bfffff%s|c00ffffff. Você não é elegivel para esta Missão."
 L["A World Quest Group Finder user has joined!"] = "Um usuario do World Quest Group Finder entrou !"
 L["A group of World Quest Group Finder users has joined!"] = "Um grupo de usuarios do World Quest Group Finder entraram!"
 L["You are currently queued in the Dungeon Finder. Please leave the queue and try again."] = "Você esta em fila para Masmorras. Por favor saia e tente novamente"
 L["You are currently queued in the Raid Finder. Please leave the queue and try again."] = "Você esta em fila para Raides. Por favor saia e tente novamente"
 L["You are currently queued for a battleground. Please leave the queue and try again."] = "Você esta em fila para Campos de batalha. Por favor saia e tente novamente"
 L["This world quest cannot be accomplished as a group."] = "Essa Missão Mundial não pode ser feita em grupo."
 L["None of your applications for |c00bfffff%s|c00ffffff were answered in time. Trying to find new groups..."] = "Nenhum de seus convites para |c00bfffff%s|c00ffffff respondeu a tempo. Tentando achar um novo grupo..."
 L["|c0000ffffWARNING:|c00ffffff This group is in raid mode which means you won't be able to complete the world quest. You should ask the leader to switch back to party mode if possible. The group will automatically switch to party mode if you become the leader."] = "|c0000ffffATTENTION:|c00ffffff Esta grupo esta convertido para Raide, isso significa que você não pode completar a Missão Mundial. Você pode pedir para o lider converter novamente para grupo se possivel. Esse grupo sera convertido automaticamente se você se tornar o Lider."
 L["You have cancelled your apply for |c00bfffff%s|c00ffffff's group for |c00bfffff%s|c00ffffff. WQGF will not try to join this group again until you relog or clear the leaders blacklist."] = "Você cancelou seu convite para o grupo |c00bfffff%s|c00ffffff' para |c00bfffff%s|c00ffffff. WQGF não ira tentar se juntar a este grupo novamente a´te você relogar ou limpar a Lista Negra."
 L["An error has occured when trying to create a new group finder entry. Please retry."] = "Um erro ocorreu enquanto tentava criar uma nova entrada de Grupo. Por favor tente de novo"
 L["You are not the group leader."] = "Você não é o lider do grupo."
 
 -- Dialogs
 L["You have completed the world quest.\n\nWould you like to leave the group or delist it from the Group Finder?"] = "Você completou essa Missão Mundial.\n\nGostaria de sair do grupo ou retira-lo da Busca ?"
 L["You have completed the world quest.\n\nWould you like to leave the group?"] = "Você completou esta Missão Mundial.\n\nVocê gostaria de sair do grupo ?"
 L["Leave"] = "Sair"
 L["Stay"] = "Ficar"
 L["Delist"] = "Retirar"
 L["Yes"] = "Sim"
 L["No"] = "Não"
 L["Cancel"] = "Cancelar"
 L["You are currently grouped for another world quest.\n\nAre you sure to want to start another one?"] = "Você esta no mento em grupo para outra Missão Mundial.\n\nVocê tem certeza que gostaria de começar outra?"
 L["You have entered a new world quest area.\n\nWould you like to find a group for \"%s\"?"] = "Você entrou na area de uma nova Missão Mundial.\n\nGostaria de procurar um novo grupo para \"%s\" ?"
 L["You have entered a new world quest area, but are currently grouped for another world quest.\n\nWould you like to leave your current group and find another for \"%s\"?"] = "Você entrou na area de uma nova Missão Mundial, mas ja esta em grupo para outra Missão.\n\nGostaria de sai do grupo atual e procurar um novo para \"%s\" ?"
 
 -- Configuration
 L["Brought to you by Robou, EU-Hyjal"] = "Trazido para você por Robou, EU-Hyjal"
 L["Enable"] = "Ativar"
 L["Enable world quest end dialog"] = "Ativar dialogo final para Missão Mundial"
 L["Enable party notification"] = "Ativar notificação de grupo"
 L["A message will be sent to the party when the world quest is completed"] = "Uma mensagem sera enviada para o grupo quando a Missão Mundial for completada"
 L["Auto-invite"] = "Convite automatico"
 L["Auto-invite WQGF users"] = "Convite automatico de usuarios do WQGF"
 L["World Quest Group Finder users will automatically be invited to the group"] = "Usuarios WQGF irão ser convidados automaticamente para o grupo"
 L["Use WoW's auto-invite function"] = "Usar a função do WoW de convite automatico"
 L["Use WoW's auto-invite function (Not recommended, will cause realm hoppers to join the group)"] = "Utilizar a função do WOW de convite automatico (não recomendado, ira causar a entrada no grupo de usuarios de outro Reino)"
 L["Auto-invite everyone"] = "Convide automaticamente todo mundo"
 L["Every applicant will automatically be invited to the group up to a limit of 5 players"] = "Toda candidato sera convidado para o grupo até o limite de 5 jogadores "
 L["Show a dialog to leave the group when the world quest is completed"] = "Mostra um dialogo para sair do grupo quando a Missão Mundial for completada"
 L["Notify the group when the world quest is completed"] = "Notifique o grupo quando a Missão Mundial for completada"
 L["The groups found by the addon are filtered by realm language according to your selection in the Group Finder interface."] = "O grupo encontrado pelo ADDON é filtrado por Reino e Indioma de acordo com sua seleção na interface de Busca de Grupos."
 L["It is recommended to select all languages to get a broader realm selection."] = "è recomendado que você selecione todos os Indiomas para expandir a seleção."
 L["Propose searching for a group when entering a world quest area for the first time"] = "Proponha procurar por um grupo quando entrar em uma area de Missão Mundial pela primeira vez"
 L["Do not propose if already grouped for another world quest"] = "Não proponha se ja estiver em grupo para outra Missão Mundial"
 L["You will be asked if you want to search for a group when entering a new world quest zone"] = "Sera perguntado se quer porcurar um grupo quando entrar emuma nova zona de Missão Mundial"
 L["Automatically start searching if not in a group"] = "Automaticamente começar a buscar se não estiver em grupo"
 L["A group will automatically be searched when entering a new world quest zone"] = "Um grupo ira automaticamente ser buscado quando entrar em uma nova zona de Missão Mundial"
 L["Enable new world quest zone detection"] = "Ativar detecção de nova zona de Missão Mundial"
 L["You will be proposed to leave the group or delist it when the world quest is completed"] = "Ira ser proposto a você para sair do grupo ou retira-lo da lista quando a Missão Mundial for completada "
 L["WQGF login message"] = "Mensagem de login do WQGF"
 L["Won't display the WQGF message at login anymore"] = "Não mostre mais a mensagem de login do WQGF"
 L["Hide WQGF init message at login"] = "Esconda a mensagem inicial do WQGF ao logar"
 L["Auto-accept group invites"] = "Aceitar automaticamente convites de grupo"
 L["Automatically accept group invites for groups applied by WQGF"] = "Automaticamente aceita convites de grupo feitos pelo WQGF"
 L["Will automatically accept group invites"] = "Irá automaticamente aceitar os convites de grupo"
 L["TRANSLATION_INFO"] = "Versão em portugues por Lobeom"
 
 -- Slash commands
 L["|c00bfffffSlash commands (/wqgf):"] = "|c00bfffffComandos de barra (/wqgf):"
 L["|c00bfffff /wqgf config : Open addon configuration"] = "|c00bfffff /wqgf config : Abre a configuração do ADDON"
 L["|c00bfffff /wqgf unbl : Clear the leaders blacklist"] = "|c00bfffff /wqgf unbl : Limpa a lista negra de lideres"
 L["Current world quest ID is |c00bfffff%s|c00ffffff."] = "ID da Missão Mundial atual é |c00bfffff%s"
 L["No current world quest."] = "Sem Missão Mundial autal."
 L["World quest zones entered this session :"] = "Zonas de Missão Mundial entradas nessa seção:"
 L["The leaders blacklist has been cleared."] = "A lista negra de lideres foi limpa."
 L["Global configuration :"] = "Configuração global:"
 L["Character configuration :"] = "Configuração de personagem:"
 L["Debug mode is now enabled."] = "Modo Debug esta ligado."
 L["Debug mode is now disabled."] = "Modo Debug esta desligado."
 
 -- Debug
 L["Debug mode is enabled"] = "Modo Debug esta ligado"
 L["Received addon message. Sender: %s. Message: %s."] = "Mensagem do ADDOn recebida. Remetente : %s. Mensagem: %s."
 L["Auto-inviting WQGF user(s). New member(s): %d. Current members count: %d."] = "Convidando automaticamente o usuario de WQGF. Novo(s) membro(s): %d. Qtd atual de membros: %d."
 L["Auto-inviting WQGF user(s). New member(s): %d. Current members count: %d."] = "Convidando automaticamente o usuario de WQGF. Novo(s) membro(s): %d. Qtd atual de membros: %d."
 L["Application has changed status. ID: %d. New status: %s."] = "O convite mudou de estado. ID: %d. Novo estado: %s."
 L["The timeout timer has been stopped."] = "O temporizador de tempo limite foi parado."
 L["The timeout timer has ended (%d seconds)"] = "O temporizador de tempo limite terminou (%d segundos)"
 L["Ignoring group because leader is blacklisted. ID: %d, Name: %s, Leader: %s"] = "Ignorando um grupo pois o lider esta na lista negra. ID: %d, Nome: %s, Lider: %s"
 L["Applying to group. ID: %d, Name: %s, Leader: %s"] = "Convidando ao grupo. ID: %d, Nome: %s, Lider: %s"
 L["World quest has been clicked. ID: %d"] = "Missão Mundial clicada. ID: %d"
 L["Clicked world quest is not the same is current (%d). Showing NEW_WORLD_QUEST_PROMPT."] = "Missão Mundial clicada não é a mesma da atual (%d). Mostrando NEW_WORLD_QUEST_PROMPT."
 L["Looking for a group for a world quest. ID: %d"] = "Procurando por um grupo para a Missão Mundial. ID: %d"
 L["World quest starting process. ID: %d"] = "Iniciando o processo da Missão Mundial. ID: %d"
 L["World quest ending process. ID: %d"] = "Finalizando o processo da Missão Mundial. ID: %d"
 L["Changed parameter value. Parameter: %s, Value: %s, Type: %s"] = "Valor do parametro mudou. Parametro: %s, Valor: %s, Tipo: %s"
 L["Failed group data: CurrentZone: %d, Title: %s, AutoInvite: %s"] = "Dados do grupo falhou: ZonaAtual: %d, Titulo: %s, AutoInvite: %s"
 L["Sending broadcast. Message: %s"] = "Enviando transMissão. Mensagem: %s"
 L["Retrieved saved current world quest info. Still in group. Restoring..."] = "Recuperando informação salva da Missão Mundial atual. Ainda em grupo. Restaurando..."
 L["Retrieved saved current world quest info. No longer in group. Deleting..."] = "Recuperando informação salva da Missão Mundial atual. Não esta em grupo. Apagando..."
 L["Setting quest #%d as visited"] = "Marcando a Missão #%d ccomo visitada"
 L["Showing dialog %s"] = "Mostrando o dialogo %s"
 L["Failed to show dialog %s"] = "Falha ao mostra o dialogo %s"
 L["Hiding dialog %s"] = "Escondendo o dialogo %s"
 L["World quest #%d zone has already been visited. Dialog will not be shown."] = "A zona de Missão Mundial #%d ja foi visitada. o dialogo não sera mostrado."
 L["Auto-accepting group invite (ID: %d)"] = "Aceitando automaticamente o convite de grupo (ID: %d)"
 L["Quest completed. (ID: %d)"] = "Missão concluída. (ID: %d)"
 L["World quest start process failed. ID: %d"] = "Processo de inicialização de MIssão Mundial falhou. ID: %d"
 
end